#arquivo se configuração do Yesod.
#Alterações mais abaixo nos coments
static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000" # NB: The port `yesod devel` uses is distinct from this value. Set the `yesod devel` port from the command line.
ip-from-header: "_env:IP_FROM_HEADER:false"


#FOI NECESSÁRIO MUDAR O USER E PASS PARA 'myblog' (antes era 'MyBlog').
#O NOME ANTERIOR (CamelCase) FOI CRIADO AUTOMATICAMENTE.
#AGORA, PORQUE DIABOS UMA COISA QUE É CRIADO AUTOMÁTICO PELA FERRAMENTA SÓ FUNCIONA
#COM MODIFICAÇÕES PELO PROGRAMADOR? QUE FERRAMENTA FAZ ISSO?

database:
  user:     "_env:PGUSER:myblog"
  password: "_env:PGPASS:myblog"
  host:     "_env:PGHOST:localhost"
  port:     "_env:PGPORT:5432"
 
  database: "_env:PGDATABASE:myblog"
  poolsize: "_env:PGPOOLSIZE:10"

copyright: Insert copyright statement here

